services:
  segurapass_backend:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${IMAGE_NAME}
    ports:
      - "8080:8080"
    env_file:
      - ${REMOTE_ENV_FILE}
    volumes:
      - ${REMOTE_KEYS_DIR}:/app/keys:ro
    restart: unless-stopped
