spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passwordmanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: password_manager
    liquibase-schema: password_manager
  jpa:
    hibernate:
      ddl-auto: validate

app:
  security:
    private-key-path: src/main/resources/keys/private.pem
    public-key-path: src/main/resources/keys/public.pem