spring:
  application:
    name: segurapass
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: password_manager
    liquibase-schema: public
  profiles:
    active: prod
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  app-version: @project.version@
  protocol-version: @segurapass.protocol.version@
  base:
    url: ${SERVER_URL:https://segurapass.xyz}
  security:
    private-key-path: ${PRIVATE_KEY_PATH}
    public-key-path: ${PUBLIC_KEY_PATH}
    totp-encryption-key: ${TOTP_SECRET_ENCRYPTION_KEY}
  email:
    url: ${EMAIL_SERVICE_URL:}
    active: ${EMAIL_SERVICE_ACTIVE:false}
    email-hash-salt: ${EMAIL_HASH_SALT:}
  rate-limiting:
    ip-enabled: ${IP_LIMITING_ENABLED:false}
    default-window-seconds: ${DEFAULT_LIMITING_SECONDS:60}