spring.application.name=passwordmanager
server.port=9000

#spring.datasource.url=jdbc:postgresql://localhost:5432/passwordmanager
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=20
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#app.security.private-key-path=src/main/resources/keys/private.pem
#app.security.public-key-path=src/main/resources/keys/public.pem

app.security.private-key-path=keys/private.pem
app.security.public-key-path=keys/public.pem

app.base.url=https://segurapass.xyz

aws.accessKey=${AWS_ACCESSKEY}
aws.secretKey=${AWS_SECRETKEY}
aws.region=${AWS_REGION}
aws.fromEmail=verification@segurapass.xyz
