spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passwordmanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  security:
    private-key-path: src/main/resources/keys/private.pem
    public-key-path: src/main/resources/keys/public.pem