spring:
  application:
    name: segurapass
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: password_manager
    liquibase-schema: password_manager
  profiles:
    active: prod
#  data:
#    redis:
#      host: localhost
#      port: 6379

app:
  base:
    url: https://segurapass.xyz
  latest:
    version: ${LATEST_VERSION:0.0.1}
    update-time: ${LATEST_UPDATE_TIME:na}
    description: ${LATEST_APP_DESCRIPTION:latest}
    download-url: ${LATEST_DOWNLOAD_URL:test.com}
  security:
    private-key-path: ${PRIVATE_KEY_PATH}
    public-key-path: ${PUBLIC_KEY_PATH}
    email-hash-salt: ${EMAIL_HASH_SALT}

aws:
  accessKey: ${AWS_ACCESSKEY:accesskey}
  secretKey: ${AWS_SECRETKEY:secretkey}
  region: ${AWS_REGION:region}
  fromEmail: verification@segurapass.xyz